# Generated by Django 4.2 on 2025-08-25 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_maplocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='image_data',
            field=models.CharField(default='Not Available', max_length=1000),
        ),
        migrations.AlterField(
            model_name='reel',
            name='image',
            field=models.URLField(default='https://i.pinimg.com/736x/ab/45/51/ab4551ae1a25886a96554c1244be395c.jpg', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='story',
            name='image',
            field=models.URLField(default='https://i.pinimg.com/736x/ab/45/51/ab4551ae1a25886a96554c1244be395c.jpg', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.URLField(default='https://i.pinimg.com/736x/ab/45/51/ab4551ae1a25886a96554c1244be395c.jpg', max_length=500),
            preserve_default=False,
        ),
    ]
